includes:
- ./defaults.yaml

dataset_config:
  masked_coco:
    return_features_info: true
    use_images: false
    use_features: true
    features:
      train:
      - datasets/coco/features/lmdbs/coco_trainval2014.lmdb
      - datasets/coco/features/lmdbs/coco_trainval2014.lmdb
    annotations:
      train:
      - datasets/coco/imdbs/imdb_karpathy_train_by_image.npy
      - datasets/coco/imdbs/imdb_karpathy_val_by_image.npy
